version: "3.9"

services:
  backend:
    build: ./backend
    container_name: weshare-backend
    env_file: ./backend/backend.env
    command: gunicorn weshare.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    restart: always
    security_opt:
      - no-new-privileges:true

  frontend:
    build: ./frontend
    container_name: weshare-frontend
    ports:
      - "8080:80"
    restart: always
    security_opt:
      - no-new-privileges:true

  db:
    image: postgres:15-alpine
    container_name: weshare-db
    env_file: ./backend/weshare/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: weshare-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
